In [ ]:
import numpy as np
a=[1,2,3,4,5]
b=np.array(a)
c=np.array([1,3,5])
print(a)
print(b)
print(c)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1 3 5]


In [ ]:
b=a
c=a.copy()
b[0]=99
print(a)
print(b)
print(c)

[99, 2, 3, 4, 5]
[99, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [ ]:
print(b[2])
print(a[2])
print(c[-1])
print(c[0:2])

3
3
5
[1, 2]


In [ ]:
a=[1,2,3,4,5]
b=np.array(a)
c=np.array([1,3,5])
print(a*2)
print(b*2)
print(c+3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[4 6 8]


In [ ]:
a=np.array([1,2,3],dtype=int)
b=np.array([1,1,2,2,3,3],dtype=float)
a1=np.array([1,2,3],dtype=float)
c=np.array([1,1,0],dtype=bool)

print(a)
print(b)
print(a1)
print(c)

[1 2 3]
[1. 1. 2. 2. 3. 3.]
[1. 2. 3.]
[ True  True False]


In [ ]:
print(np.array([-1,-3,1,0,5,7], dtype=bool))

[ True  True  True False  True  True]


In [ ]:
b=np.array([ [  [1,2], [3,4] ], [  [5,6], [7,8] ], [  [9,10], [11,12] ]])
print(b)
print(b[0][1][1])

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
4


In [ ]:
print(b.ndim)
print(b.shape)
print(b.dtype)

3
(3, 2, 2)
int64


In [ ]:
a=np.ones((2,2), dtype=int)
print(a)

[[1 1]
 [1 1]]


In [ ]:
b=np.ones_like(10, dtype=int)
print(b)

1


In [ ]:
a=np.identity(10, dtype=int)
b=np.eye(7,7,k=2,dtype=int)
c=np.eye(7,7,k=-2,dtype=int)
print(a)
print('\n\n')
print(b)
print('\n\n')
print(c)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]



[[0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]



[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]]


In [ ]:
a=np.eye(7,7, k=-6, dtype=int)
print(a)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]


In [ ]:
print(np.arange(0,11,step=5))

[ 0  5 10]


In [ ]:
print(np.linspace(0,10, num=5, endpoint=False, retstep=False))

[0. 2. 4. 6. 8.]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a[0:8:3])

[1 4 7]


In [ ]:
a=np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9]
])
print(a[:, 1:] )

[[2 3]
 [5 6]
 [8 9]]


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a.shape = (6,2) #튜플 (행 열)의 형태로 변환.
print(a)
a.shape = (4,3)
print(a)
a.shape = (5,3)
print(a)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


ValueError: ignored

In [ ]:
a=np.array([[[1,2,3],[4,5,6]],
           [[7,8,9],[10,11,12]],
           [[13,14,15],[16,17,18]]]) # (3,2,3) : (페이지,행,열)
print(a)
a.shape = (2,3,3) # (2,3,3)
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.ones(3,dtype=int) # [1,1,1]
print(a)
print('-'*30)
print(b)
print('-'*30)
print(a+b)
print('-'*30)
print(a-b)
print('-'*30)
print(a*b)
print('-'*30)
print(a/b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[1 1 1]
------------------------------
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
------------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(a*b)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,3],[2,4]])
print(a*b)
print('-'*30)

ma=np.mat(a)
mb=np.mat(b)
print(ma*mb)

[[ 1  6]
 [ 6 16]]
------------------------------
[[ 5 11]
 [11 25]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.hstack([a,b])
d=np.vstack([a,b])
print(c)
print('-'*30)
print(d)

[[1 2 5 6]
 [3 4 7 8]]
------------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
equation1=np.poly1d([1,2],True)
print(equation1)

   2
1 x - 3 x + 2


In [ ]:
equation2=np.poly1d([1,2],False)
print(equation2)

 
1 x + 2
